//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDataType
    {
        public AppDataType()
        {
            this.EquipmentAttributes = new HashSet<EquipmentAttribute>();
        }
    
        public System.Guid appDataTypeUid { get; set; }
        public string appDataType1 { get; set; }
    
        public virtual ICollection<EquipmentAttribute> EquipmentAttributes { get; set; }
    }
}
