//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersExtension
    {
        public System.Guid aspNetUsersExtensionUid { get; set; }
        public string aspnetUserUid { get; set; }
        public string name { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
