//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarDayTask
    {
        public System.Guid calendarDayTaskUid { get; set; }
        public System.Guid calendarDayUid { get; set; }
        public Nullable<System.Guid> projectUid { get; set; }
        public Nullable<System.Guid> locationUid { get; set; }
        public string task { get; set; }
    
        public virtual CalendarDay CalendarDay { get; set; }
        public virtual Location Location { get; set; }
        public virtual Project Project { get; set; }
    }
}
