//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionIssue
    {
        public CommissionIssue()
        {
            this.CommissionAttachments = new HashSet<CommissionAttachment>();
            this.CommissionNotes = new HashSet<CommissionNote>();
        }
    
        public System.Guid commissionIssueUid { get; set; }
        public System.Guid equipmentUid { get; set; }
        public System.Guid commissionStatusUid { get; set; }
        public Nullable<System.Guid> projectUserUid { get; set; }
        public string commissionIssue1 { get; set; }
        public string aspNetUserUidAsCreated { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<CommissionAttachment> CommissionAttachments { get; set; }
        public virtual CommissionStatu CommissionStatu { get; set; }
        public virtual ProjectUser ProjectUser { get; set; }
        public virtual ICollection<CommissionNote> CommissionNotes { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
