//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionAttachment
    {
        public System.Guid commissionAttachmentUid { get; set; }
        public System.Guid commissionIssueUid { get; set; }
        public string commissionAttachment1 { get; set; }
        public byte[] document { get; set; }
        public string fileType { get; set; }
        public string documentName { get; set; }
    
        public virtual CommissionIssue CommissionIssue { get; set; }
    }
}
