//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionStatu
    {
        public CommissionStatu()
        {
            this.CommissionIssues = new HashSet<CommissionIssue>();
        }
    
        public System.Guid commissionStatusUid { get; set; }
        public string commissionStatus { get; set; }
        public string commissionStatusDescription { get; set; }
        public string behaviorIndicator { get; set; }
        public Nullable<int> listOrder { get; set; }
    
        public virtual ICollection<CommissionIssue> CommissionIssues { get; set; }
    }
}
