//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletionCategory
    {
        public CompletionCategory()
        {
            this.LocationCompletionCategories = new HashSet<LocationCompletionCategory>();
        }
    
        public System.Guid completionCategoryUid { get; set; }
        public string completionCategory1 { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<LocationCompletionCategory> LocationCompletionCategories { get; set; }
    }
}
