//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorContact
    {
        public ContractorContact()
        {
            this.Eddresses = new HashSet<Eddress>();
        }
    
        public System.Guid contractorContactUid { get; set; }
        public System.Guid contractorUid { get; set; }
        public string jobTitle { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual ICollection<Eddress> Eddresses { get; set; }
    }
}
