//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorSchedule
    {
        public ContractorSchedule()
        {
            this.ContractorScheduleTasks = new HashSet<ContractorScheduleTask>();
        }
    
        public System.Guid contractorScheduleUid { get; set; }
        public System.Guid masterScheduleUid { get; set; }
        public System.Guid contractorUid { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual MasterSchedule MasterSchedule { get; set; }
        public virtual ICollection<ContractorScheduleTask> ContractorScheduleTasks { get; set; }
    }
}
