//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorNoteType
    {
        public ContractorNoteType()
        {
            this.ContractorNotes = new HashSet<ContractorNote>();
        }
    
        public System.Guid contractorNoteTypeUid { get; set; }
        public string contractorNoteType1 { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<ContractorNote> ContractorNotes { get; set; }
    }
}
