//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public Contractor()
        {
            this.ContractorContacts = new HashSet<ContractorContact>();
            this.ContractorUsers = new HashSet<ContractorUser>();
            this.Estimates = new HashSet<Estimate>();
        }
    
        public System.Guid contractorUid { get; set; }
        public string contractorName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> engScopeCompleted { get; set; }
        public Nullable<System.DateTime> contractorSelected { get; set; }
    
        public virtual ICollection<ContractorContact> ContractorContacts { get; set; }
        public virtual ICollection<ContractorUser> ContractorUsers { get; set; }
        public virtual ICollection<Estimate> Estimates { get; set; }
    }
}
