//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorClassification
    {
        public ContractorClassification()
        {
            this.Contractors = new HashSet<Contractor>();
        }
    
        public System.Guid contractorClassificationUid { get; set; }
        public string contractorClassification1 { get; set; }
        public string contractorClassificationDescription { get; set; }
    
        public virtual ICollection<Contractor> Contractors { get; set; }
    }
}
