//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public Contractor()
        {
            this.ContractorContacts = new HashSet<ContractorContact>();
            this.ContractorUsers = new HashSet<ContractorUser>();
            this.ProjectRFIs = new HashSet<ProjectRFI>();
            this.ContractorDraws = new HashSet<ContractorDraw>();
            this.ContractorSignoffs = new HashSet<ContractorSignoff>();
            this.ContractorSignoffFinals = new HashSet<ContractorSignoffFinal>();
            this.EquipmentTypeTaskAssignments = new HashSet<EquipmentTypeTaskAssignment>();
            this.ContractorNotes = new HashSet<ContractorNote>();
            this.ContractorSchedules = new HashSet<ContractorSchedule>();
            this.Estimates = new HashSet<Estimate>();
        }
    
        public System.Guid contractorUid { get; set; }
        public string contractorName { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> engScopeCompleted { get; set; }
        public Nullable<System.DateTime> contractorSelected { get; set; }
        public string contractorGroup { get; set; }
        public Nullable<System.Guid> contractorClassificationUid { get; set; }
    
        public virtual ICollection<ContractorContact> ContractorContacts { get; set; }
        public virtual ICollection<ContractorUser> ContractorUsers { get; set; }
        public virtual ICollection<ProjectRFI> ProjectRFIs { get; set; }
        public virtual ICollection<ContractorDraw> ContractorDraws { get; set; }
        public virtual ICollection<ContractorSignoff> ContractorSignoffs { get; set; }
        public virtual ICollection<ContractorSignoffFinal> ContractorSignoffFinals { get; set; }
        public virtual ICollection<EquipmentTypeTaskAssignment> EquipmentTypeTaskAssignments { get; set; }
        public virtual ICollection<ContractorNote> ContractorNotes { get; set; }
        public virtual ICollection<ContractorSchedule> ContractorSchedules { get; set; }
        public virtual ICollection<Estimate> Estimates { get; set; }
        public virtual ContractorClassification ContractorClassification { get; set; }
    }
}
