//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCode
    {
        public CostCode()
        {
            this.Contractors = new HashSet<Contractor>();
            this.ExpenseConstructions = new HashSet<ExpenseConstruction>();
            this.ExpenseMonthlies = new HashSet<ExpenseMonthly>();
        }
    
        public System.Guid costCodeUid { get; set; }
        public int costCode1 { get; set; }
        public string costCodeDescription { get; set; }
        public string jciCodeDescription { get; set; }
    
        public virtual ICollection<Contractor> Contractors { get; set; }
        public virtual ICollection<ExpenseConstruction> ExpenseConstructions { get; set; }
        public virtual ICollection<ExpenseMonthly> ExpenseMonthlies { get; set; }
    }
}
