//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMExclusionResponse
    {
        public System.Guid ecmExclusionResponseUid { get; set; }
        public int ecmExclusionResponseID { get; set; }
        public System.Guid ecmExclusionUid { get; set; }
        public string ecmExclusionResponse1 { get; set; }
    
        public virtual ECMExclusion ECMExclusion { get; set; }
    }
}
