//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMExceptionResponse
    {
        public System.Guid ecmExceptionResponseUid { get; set; }
        public int ecmExceptionResponseID { get; set; }
        public System.Guid ecmExceptionUid { get; set; }
        public string ecmExceptionResponse1 { get; set; }
    
        public virtual ECMException ECMException { get; set; }
    }
}
