//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMException
    {
        public ECMException()
        {
            this.ECMExceptionResponses = new HashSet<ECMExceptionResponse>();
        }
    
        public System.Guid ecmExceptionUid { get; set; }
        public int ecmExceptionID { get; set; }
        public System.Guid ecmUid { get; set; }
        public string ecmException1 { get; set; }
    
        public virtual ECM ECM { get; set; }
        public virtual ICollection<ECMExceptionResponse> ECMExceptionResponses { get; set; }
    }
}
