//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMExclusion
    {
        public ECMExclusion()
        {
            this.ECMExclusionResponses = new HashSet<ECMExclusionResponse>();
        }
    
        public System.Guid ecmExclusionUid { get; set; }
        public int ecmExclusionID { get; set; }
        public System.Guid ecmUid { get; set; }
        public string ecmExclusion1 { get; set; }
    
        public virtual ECM ECM { get; set; }
        public virtual ICollection<ECMExclusionResponse> ECMExclusionResponses { get; set; }
    }
}
