//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMInclusionResponse
    {
        public System.Guid ecmInclusionResponseUid { get; set; }
        public int ecmInclusionResponseID { get; set; }
        public System.Guid ecmInclusionUid { get; set; }
        public string ecmInclusionResponse1 { get; set; }
    
        public virtual ECMInclusion ECMInclusion { get; set; }
    }
}
