//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMInclusion
    {
        public ECMInclusion()
        {
            this.ECMInclusionResponses = new HashSet<ECMInclusionResponse>();
        }
    
        public System.Guid ecmInclusionUid { get; set; }
        public int ecmInclusionID { get; set; }
        public System.Guid ecmUid { get; set; }
        public string ecmInclusion1 { get; set; }
    
        public virtual ECM ECM { get; set; }
        public virtual ICollection<ECMInclusionResponse> ECMInclusionResponses { get; set; }
    }
}
