//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECMPDFSnippet
    {
        public System.Guid ecmPDFSnippetUid { get; set; }
        public System.Guid ecmUid { get; set; }
        public byte[] pdfSnippet { get; set; }
        public string pdfSnippetFileName { get; set; }
    
        public virtual ECM ECM { get; set; }
    }
}
