//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eddress
    {
        public System.Guid eddressUid { get; set; }
        public System.Guid contractorContactUid { get; set; }
        public string eddress1 { get; set; }
        public Nullable<bool> isPrimary { get; set; }
    
        public virtual ContractorContact ContractorContact { get; set; }
    }
}
