//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentNote
    {
        public System.Guid equipmentNoteUid { get; set; }
        public System.Guid equipmentUid { get; set; }
        public Nullable<System.Guid> equipmentNoteTypeUid { get; set; }
        public string equipmentNote1 { get; set; }
        public System.DateTime date { get; set; }
        public string aspNetUserUidAsCreated { get; set; }
    
        public virtual EquipmentNoteType EquipmentNoteType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
