//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentNoteType
    {
        public EquipmentNoteType()
        {
            this.EquipmentNotes = new HashSet<EquipmentNote>();
        }
    
        public System.Guid equipmentNoteTypeUid { get; set; }
        public string equipmentNoteType1 { get; set; }
        public string equipmentNoteTypeDescription { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<EquipmentNote> EquipmentNotes { get; set; }
    }
}
