//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentTaskDetailItem
    {
        public System.Guid equipmentTaskDetailItemUid { get; set; }
        public System.Guid equipmentTaskDetailUid { get; set; }
        public System.Guid equipmentToDoUid { get; set; }
        public Nullable<System.Guid> contractorUidAsAssigned { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual EquipmentTaskDetail EquipmentTaskDetail { get; set; }
        public virtual EquipmentToDo EquipmentToDo { get; set; }
    }
}
