//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAttributeType
    {
        public EquipmentAttributeType()
        {
            this.EquipmentAttributes = new HashSet<EquipmentAttribute>();
            this.EquipmentAttributeTypeTasks = new HashSet<EquipmentAttributeTypeTask>();
            this.EquipmentTypeTaskAssignments = new HashSet<EquipmentTypeTaskAssignment>();
            this.Equipments = new HashSet<Equipment>();
        }
    
        public System.Guid equipmentAttributeTypeUid { get; set; }
        public string equipmentAttributeType1 { get; set; }
        public string behaviorIndicator { get; set; }
        public bool excludeFromDropDown { get; set; }
    
        public virtual ICollection<EquipmentAttribute> EquipmentAttributes { get; set; }
        public virtual ICollection<EquipmentAttributeTypeTask> EquipmentAttributeTypeTasks { get; set; }
        public virtual ICollection<EquipmentTypeTaskAssignment> EquipmentTypeTaskAssignments { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
