//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAttributeValue
    {
        public System.Guid equipmentAttributeValueUid { get; set; }
        public System.Guid equipmentAttributeUid { get; set; }
        public System.Guid equipmentUid { get; set; }
        public string equipmentAttributeValue1 { get; set; }
    
        public virtual EquipmentAttribute EquipmentAttribute { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
