//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Equipment1 = new HashSet<Equipment>();
            this.EquipmentAttributeValues = new HashSet<EquipmentAttributeValue>();
            this.EquipmentToDoes = new HashSet<EquipmentToDo>();
            this.EquipmentAttachments = new HashSet<EquipmentAttachment>();
        }
    
        public System.Guid equipmentUid { get; set; }
        public System.Guid equipmentAttributeTypeUid { get; set; }
        public System.Guid ecmUid { get; set; }
        public System.Guid locationUid { get; set; }
        public string jciTag { get; set; }
        public string ownerTag { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string serialNumber { get; set; }
        public Nullable<System.DateTime> installDate { get; set; }
        public string area { get; set; }
        public Nullable<System.Guid> equipmentUidAsReplaced { get; set; }
        public bool isNewToSite { get; set; }
        public bool useReplacement { get; set; }
    
        public virtual ECM ECM { get; set; }
        public virtual EquipmentAttributeType EquipmentAttributeType { get; set; }
        public virtual ICollection<Equipment> Equipment1 { get; set; }
        public virtual Equipment Equipment2 { get; set; }
        public virtual ICollection<EquipmentAttributeValue> EquipmentAttributeValues { get; set; }
        public virtual ICollection<EquipmentToDo> EquipmentToDoes { get; set; }
        public virtual ICollection<EquipmentAttachment> EquipmentAttachments { get; set; }
        public virtual Location Location { get; set; }
    }
}
