//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentTypeTaskAssignment
    {
        public System.Guid equipmentTypeTaskAssignmentUid { get; set; }
        public System.Guid ecmUid { get; set; }
        public System.Guid locationUid { get; set; }
        public System.Guid contractorUid { get; set; }
        public System.Guid equipmentAttributeTypeUid { get; set; }
        public System.Guid equipmentAttributeTypeTaskUid { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual ECM ECM { get; set; }
        public virtual EquipmentAttributeType EquipmentAttributeType { get; set; }
        public virtual EquipmentAttributeTypeTask EquipmentAttributeTypeTask { get; set; }
        public virtual Location Location { get; set; }
    }
}
