//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentToDo
    {
        public System.Guid equipmentToDoUid { get; set; }
        public System.Guid equipmentUid { get; set; }
        public System.Guid equipmentTaskUid { get; set; }
        public Nullable<decimal> daysToComplete { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentTask EquipmentTask { get; set; }
    }
}
