//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAttributeTypeTask
    {
        public EquipmentAttributeTypeTask()
        {
            this.EquipmentTypeTaskAssignments = new HashSet<EquipmentTypeTaskAssignment>();
        }
    
        public System.Guid equipmentAttributeTypeTaskUid { get; set; }
        public System.Guid equipmentAttributeTypeUid { get; set; }
        public string equipmentAttributeTypeTask1 { get; set; }
        public string equipmentAttributeTypeTaskDescription { get; set; }
    
        public virtual EquipmentAttributeType EquipmentAttributeType { get; set; }
        public virtual ICollection<EquipmentTypeTaskAssignment> EquipmentTypeTaskAssignments { get; set; }
    }
}
