//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EquipmentToDoes = new HashSet<EquipmentToDo>();
        }
    
        public System.Guid equipmentUid { get; set; }
        public System.Guid ecmUid { get; set; }
        public System.Guid locationUid { get; set; }
        public string room { get; set; }
        public System.Guid equipmentTypeUid { get; set; }
        public string equipment1 { get; set; }
        public string jciCode { get; set; }
        public string barCode { get; set; }
    
        public virtual ECM ECM { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<EquipmentToDo> EquipmentToDoes { get; set; }
    }
}
