//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateException
    {
        public EstimateException()
        {
            this.EstimateExceptionResponses = new HashSet<EstimateExceptionResponse>();
        }
    
        public System.Guid estimateExceptionUid { get; set; }
        public int estimateExceptionID { get; set; }
        public System.Guid estimateUid { get; set; }
        public string estimateException1 { get; set; }
    
        public virtual ICollection<EstimateExceptionResponse> EstimateExceptionResponses { get; set; }
        public virtual Estimate Estimate { get; set; }
    }
}
