//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateExclusionResponse
    {
        public System.Guid estimateExclusionResponseUid { get; set; }
        public int estimateExclusionResponseID { get; set; }
        public System.Guid estimateExclusionUid { get; set; }
        public string estimateExclusionResponse1 { get; set; }
        public System.DateTime responseDate { get; set; }
    
        public virtual EstimateExclusion EstimateExclusion { get; set; }
    }
}
