//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateInclusionResponse
    {
        public System.Guid estimateInclusionResponseUid { get; set; }
        public int estimateInclusionResponseID { get; set; }
        public System.Guid estimateInclusionUid { get; set; }
        public string estimateInclusionResponse1 { get; set; }
        public System.DateTime responseDate { get; set; }
    
        public virtual EstimateInclusion EstimateInclusion { get; set; }
    }
}
