//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseMiscellaneousProject
    {
        public System.Guid expenseMiscellaneousProjectUid { get; set; }
        public System.Guid expenseMiscellaneousUid { get; set; }
        public System.Guid projectUid { get; set; }
        public decimal total { get; set; }
    
        public virtual ExpenseMiscellaneou ExpenseMiscellaneou { get; set; }
        public virtual Project Project { get; set; }
    }
}
