//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseConstructionDraw
    {
        public ExpenseConstructionDraw()
        {
            this.ExpenseConstructionDrawSchedules = new HashSet<ExpenseConstructionDrawSchedule>();
        }
    
        public System.Guid expenseConstructionDrawUid { get; set; }
        public System.Guid projectUid { get; set; }
        public System.Guid expenseTypeUid { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual ICollection<ExpenseConstructionDrawSchedule> ExpenseConstructionDrawSchedules { get; set; }
        public virtual Project Project { get; set; }
    }
}
