//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseConstruction
    {
        public System.Guid expenseConstructionUid { get; set; }
        public System.Guid projectUid { get; set; }
        public string expenseConstruction1 { get; set; }
        public string expenseConstructionDescription { get; set; }
        public decimal rate { get; set; }
        public System.Guid intervalUid { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.Guid> expenseTypeUid { get; set; }
        public Nullable<System.Guid> costCodeUid { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Interval Interval { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual ExpenseType ExpenseType1 { get; set; }
        public virtual CostCode CostCode { get; set; }
    }
}
