//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseConstructionDrawSchedule
    {
        public System.Guid expenseConstructionDrawScheduleUid { get; set; }
        public System.Guid expenseConstructionDrawUid { get; set; }
        public Nullable<int> drawPeriod { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual ExpenseConstructionDraw ExpenseConstructionDraw { get; set; }
    }
}
