//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval
    {
        public Interval()
        {
            this.ExpenseConstructions = new HashSet<ExpenseConstruction>();
            this.ExpenseTravels = new HashSet<ExpenseTravel>();
        }
    
        public System.Guid intervalUid { get; set; }
        public string interval1 { get; set; }
        public string intervalDescription { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<ExpenseConstruction> ExpenseConstructions { get; set; }
        public virtual ICollection<ExpenseTravel> ExpenseTravels { get; set; }
    }
}
