//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JCIEstimateEntities : DbContext
    {
        public JCIEstimateEntities()
            : base("name=JCIEstimateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<ContractorContact> ContractorContacts { get; set; }
        public virtual DbSet<ContractorUser> ContractorUsers { get; set; }
        public virtual DbSet<Eddress> Eddresses { get; set; }
        public virtual DbSet<EstimateStatu> EstimateStatus { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Estimate> Estimates { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<LineOfWork> LineOfWorks { get; set; }
        public virtual DbSet<ProjectLineOfWork> ProjectLineOfWorks { get; set; }
        public virtual DbSet<ECM> ECMs { get; set; }
    }
}
