//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineOfWork
    {
        public LineOfWork()
        {
            this.ProjectLineOfWorks = new HashSet<ProjectLineOfWork>();
        }
    
        public System.Guid lineOfWorkUid { get; set; }
        public string lineOfWork1 { get; set; }
        public string lineOfWorkDescription { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<ProjectLineOfWork> ProjectLineOfWorks { get; set; }
    }
}
