//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationIssue
    {
        public LocationIssue()
        {
            this.LocationNotes = new HashSet<LocationNote>();
        }
    
        public System.Guid locationIssueUid { get; set; }
        public string aspNetUserUidAsCreated { get; set; }
        public System.Guid locationUid { get; set; }
        public System.Guid warrantyStatusUid { get; set; }
        public string aspNetUserUid { get; set; }
        public System.DateTime date { get; set; }
        public string locationIssue1 { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual WarrantyStatu WarrantyStatu { get; set; }
        public virtual ICollection<LocationNote> LocationNotes { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
