//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Estimates = new HashSet<Estimate>();
        }
    
        public System.Guid locationUid { get; set; }
        public string location1 { get; set; }
        public string locationDescription { get; set; }
    
        public virtual ICollection<Estimate> Estimates { get; set; }
    }
}
