//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationNote
    {
        public System.Guid locationNoteUid { get; set; }
        public System.Guid locationIssueUid { get; set; }
        public string locationNote1 { get; set; }
        public System.DateTime date { get; set; }
        public string aspNetUserUidAsCreated { get; set; }
    
        public virtual LocationIssue LocationIssue { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
