//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationCompletionCategory
    {
        public System.Guid locationCompletionCategoryUid { get; set; }
        public System.Guid projectUid { get; set; }
        public System.Guid locationUid { get; set; }
        public System.Guid completionCategoryUid { get; set; }
    
        public virtual CompletionCategory CompletionCategory { get; set; }
        public virtual Location Location { get; set; }
        public virtual Project Project { get; set; }
    }
}
