//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        public Milestone()
        {
            this.MilestoneActions = new HashSet<MilestoneAction>();
        }
    
        public System.Guid milestoneUid { get; set; }
        public string milestone1 { get; set; }
        public string milestoneDescription { get; set; }
        public int defaultListOrder { get; set; }
    
        public virtual ICollection<MilestoneAction> MilestoneActions { get; set; }
    }
}
