//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestoneAction
    {
        public System.Guid milestoneActionUid { get; set; }
        public System.Guid milestoneUid { get; set; }
        public string milestoneAction1 { get; set; }
        public string milestoneActionDescription { get; set; }
        public int defaultListOrder { get; set; }
        public bool isRollingUp { get; set; }
    
        public virtual Milestone Milestone { get; set; }
    }
}
