//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        public Opportunity()
        {
            this.SalesOpportunities = new HashSet<SalesOpportunity>();
        }
    
        public System.Guid opportunityUid { get; set; }
        public string opportunity1 { get; set; }
        public string opportunityDescription { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<int> projectedProjectSize { get; set; }
        public Nullable<int> spentToDate { get; set; }
    
        public virtual ICollection<SalesOpportunity> SalesOpportunities { get; set; }
    }
}
