//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PECTask
    {
        public PECTask()
        {
            this.PECCosts = new HashSet<PECCost>();
        }
    
        public System.Guid pecTaskUid { get; set; }
        public string pecTask1 { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<PECCost> PECCosts { get; set; }
    }
}
