//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRFIResponse
    {
        public System.Guid projectRFIResponseUid { get; set; }
        public System.Guid projectRFIUid { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string aspNetUserUidAsResponded { get; set; }
        public string projectRFIResponse1 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ProjectRFI ProjectRFI { get; set; }
    }
}
