//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskPrototype
    {
        public System.Guid projectTaskPrototypeUid { get; set; }
        public string projectTaskPrototype1 { get; set; }
        public Nullable<System.Guid> projectTaskCategoryUid { get; set; }
        public Nullable<int> sequence { get; set; }
    
        public virtual ProjectTaskCategory ProjectTaskCategory { get; set; }
    }
}
