//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCalendarDayTask
    {
        public System.Guid projectCalendarDayTaskUid { get; set; }
        public System.Guid projectCalendarDayUid { get; set; }
        public System.Guid projectUid { get; set; }
        public Nullable<System.Guid> locationUid { get; set; }
        public string aspnetUserUidAsAssigned { get; set; }
        public Nullable<System.DateTime> taskStartDate { get; set; }
        public Nullable<int> taskDuration { get; set; }
        public string task { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Location Location { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectCalendarDay ProjectCalendarDay { get; set; }
    }
}
