//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCalendarDay
    {
        public ProjectCalendarDay()
        {
            this.ProjectCalendarDayTasks = new HashSet<ProjectCalendarDayTask>();
        }
    
        public System.Guid projectCalendarDayUid { get; set; }
        public System.Guid projectCalendarUid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ProjectCalendar ProjectCalendar { get; set; }
        public virtual ICollection<ProjectCalendarDayTask> ProjectCalendarDayTasks { get; set; }
    }
}
