//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMilestone
    {
        public ProjectMilestone()
        {
            this.ProjectMilestoneActions = new HashSet<ProjectMilestoneAction>();
        }
    
        public System.Guid projectMilestoneUid { get; set; }
        public System.Guid projectUid { get; set; }
        public string projectMilestone1 { get; set; }
        public string projectMilestoneDescription { get; set; }
        public int listOrder { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectMilestoneAction> ProjectMilestoneActions { get; set; }
    }
}
