//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectScope
    {
        public System.Guid projectScopeUid { get; set; }
        public System.Guid projectUid { get; set; }
        public byte[] projectScopePDF { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
