//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAddendum
    {
        public System.Guid projectAddendumUid { get; set; }
        public System.Guid projectUid { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string aspNetUserUidAsCreated { get; set; }
        public string projectAddendum1 { get; set; }
        public int addendumId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Project Project { get; set; }
    }
}
