//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskCategory
    {
        public ProjectTaskCategory()
        {
            this.ProjectTaskPrototypes = new HashSet<ProjectTaskPrototype>();
        }
    
        public System.Guid projectTaskCategoryUid { get; set; }
        public string projectTaskCategory1 { get; set; }
    
        public virtual ICollection<ProjectTaskPrototype> ProjectTaskPrototypes { get; set; }
    }
}
