//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCalendar
    {
        public ProjectCalendar()
        {
            this.ProjectCalendarDays = new HashSet<ProjectCalendarDay>();
        }
    
        public System.Guid projectCalendarUid { get; set; }
        public string aspNetUserUid { get; set; }
        public string projectCalendar1 { get; set; }
    
        public virtual ICollection<ProjectCalendarDay> ProjectCalendarDays { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
