//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRFI
    {
        public ProjectRFI()
        {
            this.ProjectRFIResponses = new HashSet<ProjectRFIResponse>();
        }
    
        public System.Guid projectRFIUid { get; set; }
        public System.Guid projectUid { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.Guid contractorUid { get; set; }
        public System.Guid ecmUid { get; set; }
        public System.Guid rfiTypeUid { get; set; }
        public System.Guid rfiStatusUid { get; set; }
        public string aspNetUserUidAsCreated { get; set; }
        public string aspNetUserUidAsAssigned { get; set; }
        public string projectRFI1 { get; set; }
        public int projectRFIID { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Project Project { get; set; }
        public virtual RfiType RfiType { get; set; }
        public virtual ICollection<ProjectRFIResponse> ProjectRFIResponses { get; set; }
        public virtual RfiStatu RfiStatu { get; set; }
        public virtual ECM ECM { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
