//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDefinition
    {
        public System.Guid ReportDefinitionUid { get; set; }
        public string ssrsReportName { get; set; }
        public string textBox1 { get; set; }
        public string textBox2 { get; set; }
        public string textBox3 { get; set; }
        public string textBox4 { get; set; }
        public string textBox5 { get; set; }
        public string textBox6 { get; set; }
        public string textBox7 { get; set; }
        public string textBox8 { get; set; }
        public string textBox9 { get; set; }
        public string textBox10 { get; set; }
        public string textBox11 { get; set; }
        public string textBox12 { get; set; }
        public string textBox13 { get; set; }
        public string textBox14 { get; set; }
        public string textBox15 { get; set; }
        public string textBox16 { get; set; }
        public string textBox17 { get; set; }
        public string textBox18 { get; set; }
        public string textBox19 { get; set; }
        public string textBox20 { get; set; }
        public string textBox21 { get; set; }
        public string textBox22 { get; set; }
        public string textBox23 { get; set; }
        public string textBox24 { get; set; }
        public string textBox25 { get; set; }
        public Nullable<System.Guid> projectUid { get; set; }
        public string textBox26 { get; set; }
        public string textBox27 { get; set; }
        public string textBox28 { get; set; }
        public string textBox29 { get; set; }
        public string textBox30 { get; set; }
        public string textBox31 { get; set; }
        public string textBox32 { get; set; }
        public string textBox33 { get; set; }
        public string textBox34 { get; set; }
        public string textBox35 { get; set; }
        public string textBox36 { get; set; }
        public string textBox37 { get; set; }
        public string textBox38 { get; set; }
        public string textBox39 { get; set; }
        public string textBox40 { get; set; }
        public string textBox41 { get; set; }
        public string textBox42 { get; set; }
        public string textBox43 { get; set; }
        public string textBox44 { get; set; }
        public string textBox45 { get; set; }
        public string textBox46 { get; set; }
        public string textBox47 { get; set; }
        public string textBox48 { get; set; }
        public string textBox49 { get; set; }
        public string textBox50 { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
