//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RfiStatu
    {
        public RfiStatu()
        {
            this.ProjectRFIs = new HashSet<ProjectRFI>();
        }
    
        public System.Guid rfiStatusUid { get; set; }
        public string rfiStatus { get; set; }
        public string behaviorIndicator { get; set; }
        public string rowColor { get; set; }
        public Nullable<int> listOrder { get; set; }
    
        public virtual ICollection<ProjectRFI> ProjectRFIs { get; set; }
    }
}
