//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOpportunityMilestone
    {
        public System.Guid salesOpportunityMilestoneUid { get; set; }
        public System.Guid salesOpportunityUid { get; set; }
        public System.Guid milestoneUid { get; set; }
        public bool isCompleted { get; set; }
    
        public virtual Milestone Milestone { get; set; }
        public virtual SalesOpportunity SalesOpportunity { get; set; }
    }
}
