//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTeam
    {
        public SalesTeam()
        {
            this.SalesOpportunities = new HashSet<SalesOpportunity>();
            this.SalesTeamMembers = new HashSet<SalesTeamMember>();
        }
    
        public System.Guid salesTeamUid { get; set; }
        public string salesTeam1 { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<SalesOpportunity> SalesOpportunities { get; set; }
        public virtual ICollection<SalesTeamMember> SalesTeamMembers { get; set; }
    }
}
