//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOpportunityTask
    {
        public System.Guid salesOpportunityTaskUid { get; set; }
        public System.Guid salesOpportunityUid { get; set; }
        public string SalesOpportunityTask1 { get; set; }
        public System.DateTime week { get; set; }
        public bool isCompleted { get; set; }
    
        public virtual SalesOpportunity SalesOpportunity { get; set; }
    }
}
