//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.ContractorScheduleTasks = new HashSet<ContractorScheduleTask>();
        }
    
        public System.Guid shiftUid { get; set; }
        public string shift1 { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<ContractorScheduleTask> ContractorScheduleTasks { get; set; }
    }
}
