//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestGrid
    {
        public System.Guid testGridUid { get; set; }
        public string testGrid1 { get; set; }
        public Nullable<System.DateTime> testGridDate { get; set; }
    }
}
