//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoStatu
    {
        public ToDoStatu()
        {
            this.ProjectToDoes = new HashSet<ProjectToDo>();
        }
    
        public System.Guid toDoStatusUid { get; set; }
        public string toDoStatus { get; set; }
        public string toDoStatusDescription { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<ProjectToDo> ProjectToDoes { get; set; }
    }
}
