//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExpense
    {
        public System.Guid userExpenseUid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string aspNetUserUid { get; set; }
        public string userExpense1 { get; set; }
        public System.Guid userExpenseStatusUid { get; set; }
        public System.Guid userExpenseTypeUid { get; set; }
        public decimal amount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual UserExpenseStatu UserExpenseStatu { get; set; }
        public virtual UserExpenseType UserExpenseType { get; set; }
    }
}
