//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExpenseStatu
    {
        public UserExpenseStatu()
        {
            this.UserExpenses = new HashSet<UserExpense>();
        }
    
        public System.Guid userExpenseStatusUid { get; set; }
        public string userExpenseStatus { get; set; }
        public string behaviorIndicator { get; set; }
    
        public virtual ICollection<UserExpense> UserExpenses { get; set; }
    }
}
