//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__ContractorECMByCategory
    {
        public string ecmnumber { get; set; }
        public System.Guid ecmUid { get; set; }
        public System.Guid contractorUid { get; set; }
        public System.Guid categoryUid { get; set; }
        public decimal amount { get; set; }
        public decimal activeAmount { get; set; }
        public string ecmString { get; set; }
        public string contractorName { get; set; }
        public string category { get; set; }
        public System.Guid projectUid { get; set; }
        public string project { get; set; }
        public string intEcmNumber { get; set; }
    }
}
