//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__EquipmentForEcm
    {
        public System.Guid equipmentUid { get; set; }
        public Nullable<System.Guid> equipmentUidAsReplaced { get; set; }
        public System.Guid projectUid { get; set; }
        public string project { get; set; }
        public System.Guid locationUid { get; set; }
        public string location { get; set; }
        public System.Guid ecmUId { get; set; }
        public string ecmString { get; set; }
        public bool isNewToSite { get; set; }
        public bool useReplacement { get; set; }
        public Nullable<decimal> jciTag { get; set; }
        public string ownerTag { get; set; }
        public string manufacturer { get; set; }
        public string equipmentAttributeType { get; set; }
        public string model { get; set; }
        public string serialNumber { get; set; }
        public string tons { get; set; }
        public string EER { get; set; }
        public string VAC { get; set; }
        public Nullable<int> year { get; set; }
        public string phase { get; set; }
    }
}
