//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v__ExpensePercentage
    {
        public System.Guid expensePercentageUid { get; set; }
        public System.Guid projectUid { get; set; }
        public string expensePercentage { get; set; }
        public string expensePercentageDescription { get; set; }
        public decimal percentage { get; set; }
        public Nullable<decimal> sumActiveTotal { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
