//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyStatu
    {
        public WarrantyStatu()
        {
            this.WarrantyIssues = new HashSet<WarrantyIssue>();
            this.LocationIssues = new HashSet<LocationIssue>();
        }
    
        public System.Guid warrantyStatusUid { get; set; }
        public string warrantyStatus { get; set; }
        public string warrantyStatusDescription { get; set; }
        public string behaviorIndicator { get; set; }
        public Nullable<int> listOrder { get; set; }
    
        public virtual ICollection<WarrantyIssue> WarrantyIssues { get; set; }
        public virtual ICollection<LocationIssue> LocationIssues { get; set; }
    }
}
