//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCIEstimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyNote
    {
        public System.Guid warrantyNoteUid { get; set; }
        public System.Guid warrantyIssueUid { get; set; }
        public string warrantyNote1 { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual WarrantyIssue WarrantyIssue { get; set; }
    }
}
